# -*- coding: utf-8 -*-
"""task 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jixn8rWvfBrcr-9t-o8XPW_ZO0LK2nrG
"""

import pandas as pd
print("=" * 50)
print("MINI DATA ANALYSIS PROJECT")
print("=" * 50)

# 1. LOAD DATASET
df = pd.read_csv("students.csv")
print("\n--- 1. LOADING DATASET ---")
print(df.head())

# 2. DATA INSPECTION
print("\n--- 2. DATA INSPECTION ---")
print("\nDataset Shape:")
print(df.shape)
print("\nData Types:")
print(df.dtypes)
print("\nStatistical Summary:")
print(df.describe())

# 3. IDENTIFY MISSING VALUES
print("\n--- 3. MISSING VALUES ---")
print(df.isnull().sum())

# 4. HANDLE MISSING VALUES
print("\n--- 4. HANDLE MISSING VALUES ---")
df["Attendance"] = df["Attendance"].fillna(
    df["Attendance"].mean()
)
print("Missing values handled successfully!")

# 5. SELECTING AND FILTERING DATA
print("\n--- 5. FILTERING DATA ---")
high_scorers = df[df["Marks"] >= 80]
print("Students with Marks >= 80:")
print(
    high_scorers[
        ["Student_ID", "Name", "Marks", "Department"]
    ]
)

# 6. SORTING DATA
print("\n--- 6. SORTING DATA ---")
sorted_df = df.sort_values(
    by="Marks",
    ascending=False
)
print("TOP 10 STUDENTS:")
print(
    sorted_df[
        ["Student_ID", "Name", "Marks", "Department"]
    ].head(10)
)

# 7. GROUPBY ANALYSIS
print("\n--- 7. GROUPBY ANALYSIS ---")
department_summary = df.groupby(
    "Department"
).agg(
    Students=("Student_ID", "count"),
    Average_Marks=("Marks", "mean"),
    Average_Attendance=("Attendance", "mean"),
    Total_Stipend=("Monthly_Stipend", "sum")
).round(2)
print(department_summary)

# 8. PIVOT TABLE
print("\n--- 8. PIVOT TABLE ---")
pivot_table = pd.pivot_table(
    df,
    index="Department",
    values=["Marks", "Attendance"],
    aggfunc="mean"
).round(2)
print(pivot_table)

# 9. FINDING USEFUL INSIGHTS
print("\n--- 9. USEFUL INSIGHTS ---")
# Highest marks
highest_marks_row = df.loc[
    df["Marks"].idxmax()
]
# Students scoring 80 or above
high_scorer_count = (
    df["Marks"] >= 80
).sum()
# Pass percentage
pass_percentage = (
    (df["Marks"] >= 40).mean() * 100
)
# Highest average marks department
highest_average_department = (
    department_summary["Average_Marks"].idxmax()
)
print(
    "Highest Marks:",
    highest_marks_row["Marks"]
)
print(
    "Student Name:",
    highest_marks_row["Name"]
)
print(
    "Students Scoring 80 or Above:",
    high_scorer_count
)
print(
    "Pass Percentage:",
    round(pass_percentage, 2), "%"
)
print(
    "Department with Highest Average Marks:",
    highest_average_department
)

# 10. EXPORT PROCESSED DATASET
print("\n--- 10. EXPORTING DATA ---")
df.to_csv(
    "task10_processed_students.csv",
    index=False
)
print("Processed dataset exported successfully!")

# FINAL MESSAGE
print("\n" + "=" * 50)
print("TASK 10 COMPLETED SUCCESSFULLY!")
print("=" * 50)