# -*- coding: utf-8 -*-
"""task 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UKSj95JMI2PF4oyEF6I3HyNd9zjoWnAD
"""

import pandas as pd

# 1. Read the CSV file
df = pd.read_csv("students.csv")

# 2. Display the first 5 rows
print("--- First 5 Rows ---")
print(df.head())

# 3. Display the last 5 rows
print("\n--- Last 5 Rows ---")
print(df.tail())

# 4. Check the number of rows and columns
print("\n--- Shape ---")
print(df.shape)

# 5. Display column names
print("\n--- Column Names ---")
print(df.columns)

# 6. Check data types
print("\n--- Data Types ---")
print(df.dtypes)

# 7. Display information about the dataset
print("\n--- Dataset Information ---")
df.info()

# 8. Display statistical summary
print("\n--- Statistical Summary ---")
print(df.describe())