# -*- coding: utf-8 -*-
"""task 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-MWSNeta5VQ-0LOa_JL7p5FEzzAL5by
"""

import pandas as pd

# Read the CSV file
df = pd.read_csv("students.csv")

print("--- Original DataFrame ---")
print(df)

# 1. Select specific columns
print("\n--- Selected Columns ---")
print(df[["Name", "Marks"]])

# 2. Select specific rows
print("\n--- First Three Rows ---")
print(df.iloc[:3])

# 3. Filter students with marks greater than 80
print("\n--- Students with Marks Greater Than 80 ---")
print(df[df["Marks"] > 80])

# 4. Apply multiple filtering conditions
print("\n--- CSE Students with Marks Greater Than 80 ---")
filtered_df = df[(df["Department"] == "CSE") & (df["Marks"] > 80)]
print(filtered_df)

# 5. Sort data in ascending order
print("\n--- Marks in Ascending Order ---")
print(df.sort_values(by="Marks", ascending=True))

# 6. Sort data in descending order
print("\n--- Marks in Descending Order ---")
print(df.sort_values(by="Marks", ascending=False))