# -*- coding: utf-8 -*-
"""task 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTYbsOmZ7e2YBE2acWl6kJ9OOM9veT8R
"""

import pandas as pd
print("\n" + "=" * 60)
print("TASK 8: MERGE, CONCATENATE, GROUPBY & PIVOT TABLE")
print("=" * 60)
df = pd.read_csv("students.csv")
print("\nOriginal Dataset:")
print(df.head())
# 1. MERGE TWO DATAFRAMES
print("\n--- 1. MERGE ---")
# Create a second DataFrame
extra_df = pd.DataFrame({
    "Student_ID": [1001, 1002, 1003, 1004, 1005],
    "Scholarship_Status": ["Yes", "No", "Yes", "No", "Yes"],
    "Club": ["Coding", "Sports", "Coding", "Cultural", "Sports"]
})
# Merge using Student_ID
merged_df = pd.merge(
    df,
    extra_df,
    on="Student_ID",
    how="left"
)
print(merged_df.head())
# 2. CONCATENATE TWO DATAFRAMES
print("\n--- 2. CONCATENATE ---")
# Split the dataset into two parts
first_part = df.iloc[:5].copy()
second_part = df.iloc[5:10].copy()
# Combine the two DataFrames
concatenated_df = pd.concat(
    [first_part, second_part],
    ignore_index=True
)
print(concatenated_df)
# 3. GROUPBY ANALYSIS
print("\n--- 3. GROUPBY ---")
grouped_df = df.groupby("Department").agg(
    Student_Count=("Student_ID", "count"),
    Average_Marks=("Marks", "mean"),
    Minimum_Marks=("Marks", "min"),
    Maximum_Marks=("Marks", "max"),
    Average_Attendance=("Attendance", "mean")
).round(2)
print(grouped_df)
# 4. PIVOT TABLE
print("\n--- 4. PIVOT TABLE ---")
pivot_df = pd.pivot_table(
    df,
    index="Department",
    values=["Marks", "Attendance"],
    aggfunc="mean"
).round(2)
print(pivot_df)