# -*- coding: utf-8 -*-
"""task7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QnvhgE2cgeCem6NHH-gfrhCC35r4qs13
"""

import pandas as pd

# Read the CSV file
df = pd.read_csv("missing_students.csv")

print("--- Original DataFrame ---")
print(df)

# 1. Identify missing values
print("\n--- Missing Values (True/False) ---")
print(df.isnull())

# 2. Count missing values in each column
print("\n--- Missing Values Count ---")
print(df.isnull().sum())

# 3. Remove rows containing missing values
df_removed = df.dropna()

print("\n--- DataFrame After Removing Missing Rows ---")
print(df_removed)

# 4. Fill missing values using appropriate methods

# Fill missing numeric values with the column mean
df_filled = df.copy()

df_filled["Age"] = df_filled["Age"].fillna(
    df_filled["Age"].mean()
)

df_filled["Marks"] = df_filled["Marks"].fillna(
    df_filled["Marks"].mean()
)

df_filled["Monthly_Stipend"] = df_filled["Monthly_Stipend"].fillna(
    df_filled["Monthly_Stipend"].mean()
)

# Fill missing department with the most common department
df_filled["Department"] = df_filled["Department"].fillna(
    df_filled["Department"].mode()[0]
)

print("\n--- DataFrame After Filling Missing Values ---")
print(df_filled)