# -*- coding: utf-8 -*-
"""task 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXmu1HmBSxmD6AC_NlTN-ZO2AXevjQef
"""

import pandas as pd
# Load the dataset
df = pd.read_csv("students.csv")
print("ORIGINAL DATASET")
print(df.head())
# PROCESS THE DATA
# Sort the dataset by Marks
processed_df = df.sort_values(
    by="Marks",
    ascending=False
)
print("\nPROCESSED DATASET")
print(processed_df.head())
# EXPORT DATA TO CSV
processed_df.to_csv(
    "processed_students.csv",
    index=False
)
print("\nFile exported successfully!")
# VERIFY EXPORTED FILE
check_df = pd.read_csv(
    "processed_students.csv"
)
print("\nEXPORTED FILE DATA")
print(check_df.head())
print("\nRows:", check_df.shape[0])
print("Columns:", check_df.shape[1])
# FINAL MESSAGE
print("\nTASK 9 COMPLETED SUCCESSFULLY!")