import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90,100])
print("Original Array:",arr)
print("\nIndexing")
print("First Element:",arr[0])
print("Third Element:",arr[2])
print("Last Element:",arr[-1])
print("\nSlicing")
print("Elements From Index 1 to 3:",arr[1:4])
print("First Three Elements:",arr[:3])
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\nTwo Dimensional Array:",matrix)
print("\nAccessing Rows & Columns")
print("\nFirst Row",matrix[0])
print("\nSecond Row",matrix[1])
print("\nFirst Column",matrix[:,0])
print("\nElement in Row 1 & Column 2",matrix[1,2])
original=np.array([1,2,3,4,5,6])
reshaped=original.reshape(2,3)
print("\nOriginal 1D Array",original)
print("Reshaped 2D Array\n",reshaped)       